db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/postgres
db.username=postgres
db.password=1

hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG